package.json
1.6 breaks iojs. this lowers the minimum nan version so that developers can still do `nan@~1.5.1`.
=> :arrow_down: nan@^1.5.1

package.json
The issue with nan on io.js was fixed in https://github.com/rvagg/nan/pull/273. `npm install` on io.js 1.1.0 works now.
=> Change nan dependency back to ^1.6.2

index.js, src/common.cc, test/unit/io.js
This requires https://github.com/jcupitt/libvips/pull/241
=> Add support for loading images through ImageMagick as a buffer

preinstall.sh
This was needed on my docker container running Debian Jessie. This is the error without it:
```text
Package libgsf-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgsf-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libgsf-1', required by 'vips', not found
gyp: Call to 'PKG_CONFIG_PATH=":$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 1. while trying to load binding.gyp
```
=> Install libgsf-1-dev on Debian 8

README.md, index.js, package.json, src/resize.cc, test/unit/resize.js
*fixes #174*
This add a new feature `.min()` which preserves the aspect ration and resize the image to the minimum `width` or `height` specified.
On another note, we might want to make the documentation for `max()` and `min()` a bit clearer. This is how Mozilla describes the `background-size` values `contain` and `cover`:
> **cover**
> This keyword specifies that the background image should be scaled to be as small as possible while ensuring both its dimensions are greater than or equal to the corresponding dimensions of the background positioning area.
> **contain**
> This keyword specifies that the background image should be scaled to be as large as possible while ensuring both its dimensions are less than or equal to the corresponding dimensions of the background positioning area.
I …
=> feature: min

index.js, src/common.cc, test/unit/io.js
This removes the custom image fingerprinting code and uses the libvips
is_a_buffer() infrastructure instead.
This requires https://github.com/jcupitt/libvips/pull/240.
=> Let libvips check whether we received a valid image or not

index.js, package.json, src/resize.cc, test/unit/resize.js
Add an `ignoreAspectRatio` method to support resizing of images to arbitrary aspect ratios, as requested in [#118](https://github.com/lovell/sharp/issues/118).
Fixed width and height:
```javascript
sharp('foo.jpg').ignoreAspectRatio().resize(300, 300);
```
Fixed width (leaving height unchanged):
```javascript
sharp('foo.jpg').ignoreAspectRatio().resize(300);
```
Fixed height (leaving width unchanged):
```javascript
sharp('foo.jpg').ignoreAspectRatio().resize(null, 300);
```
sharp's behavior is otherwise unchanged.
* src/resize.cc
- Canvas
- Additional member `IGNORE_ASPECT`
- ResizeWorker::Execute
- Logic is mostly unchanged. Add separate x and y variables for `factor`, `shrink`, and `residual`.
- Move small amount of logic into private class methods:
- `CalculateShrink`
- …
=> Support resize without preserving aspect ratio

src/common.cc, src/resize.cc, test/unit/interpolation.js
By accident I called `interpolateWith()` with an unknown interpolator name, which resulted in a segfault.
The attached patch avoids this by checking the return values of `vips_interpolate_new` and raising an exception if this returns NULL.
=> avoid segfault with unknown interpolator

binding.gyp
Fixes the following warnings while compiling:
```
D:\Forritun\Microsoft Visual Studio 14.0\VC\include\xlocale(341): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (compiling source file ..\src\common.cc) [D:\sharp\build\sharp.vcxproj]
D:\Forritun\Microsoft Visual Studio 14.0\VC\include\xlocale(341): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (compiling source file ..\src\operations.cc) [D:\sharp\build\sharp.vcxproj]
...etc...
```
Solution taken from here: https://github.com/TooTallNate/node-gyp/issues/26#issuecomment-7296389
=> binding.gyp: Fix warnings during compiling

index.js, test/unit/crop.js
I have a [use case](https://github.com/papandreou/express-processimage/) where the gravity is taken from a query string and it's cumbersome to use the numeric values or do a lookup in `require('sharp').gravity`. Seemed like it would be easy (and desirable) to support the strings directly.
Will conflict slightly with #205, but it should be easy to resolve.
=> crop: Permit specifying the gravity as a string

preinstall.sh
Simply to add `freya` to the recognised Linux distros in the __preinstall__ script. Freya (i.e. Elementary OS 0.3) is based on Ubuntu 14.04 and the script completes successfully.
=> (preinstall) add freya to 'supported' distros

preinstall.sh
Hey @lovell, similar to my previous _pull request_ here I'm adding `wily` (Ubuntu 15.10) to the list of distros, perhaps as it is still in beta (I'm using Beta 2) this is premature but I can confirm that the preinstall script works perfectly.
=> (preinstall) add wily to 'supported' distros

docs/api.md
Line 330: "betweem" => "between"
=> Fix typo (docs/api)

docs/api.md
I noticed we can do something like `.toFile("tmp/temp.jpg")`
=> Clarify fileName argument by changing to path

binding.gyp
libvips (https://github.com/jcupitt/libvips/issues/196) use Libs.private, Requires.private options in pkg-config vips.pc files. In case static compiling libvips it is necessary use ```--static``` option with ```pkg-config``` command during compiling sharp. https://github.com/lovell/sharp/issues/169
npm install static example:
```PKG_CONFIG_PATH=/path_to_static_compiled_vips/lib/pkgconfig/ npm install --prefix=/sharp sharp --runtime_link=static```
=> Add --runtime_link=static

docs/api.md, index.js, test/unit/extract.js
Also stop encouraging the use of .extract(top,left,width,height) as discussed on #276.
=> extract: Support an options object (take 2 against the look branch)

packaging/test.sh, packaging/test/alpine.sh
This updates the alpine-linux packaging test to use the libvips-dev apk (currently being served from a custom s3 repository location; see alpinelinux/aports#29 for the upstream APK submission).
I realized that a Docker image probably isn't the most maintainable approach for distributing a compiled-library meant to be used as a base image for other projects, and found it easier to leverage the existing OS package management systems, in this case APKs (which are basically just tar-packages of the project's files, with some metadata). Following the APK conventions, the compiled `libvips` package is separated into `libvips` which is the compiled runtime library, and `libvips-dev` which includes the development headers needed for building projects linking to it. So for a packaging-test for …
=> Use libvips-dev apk for alpine-linux packaging test

docs/install.md
* Add a more detailed explanation of how sharp discovers libvips
* Add a section on packaging sharp for running on AWS Lambda
This resolves #365 and is related to #169.
=> [ci skip] Improved Linux docs, Lambda instructions

binding.gyp
This allows for a more verbose error message on mac os x
I have no idea why or how but it worked
```
libc++abi.dylib: terminating with uncaught exception of type vips::VError
```
becomes
```
libc++abi.dylib: terminating with uncaught exception of type vips::VError: VipsImage: memory area too small --- should be 1191960 bytes, you passed 1189440
```
=> tweak xcode_settings

docs/api.md, index.js, package.json, src/common.cc, src/common.h, src/pipeline.cc, src/pipeline.h, test/unit/tile.js
This adds support for the `container` option of `vips dzsave`, which writes all generated deep zoom files to a ZIP container instead of the filesystem.
To enable it you can either use the `.zip`/ `.szi` file extensions or use `.tile({container: 'zip'})` with `.toFormat('dz')` or the `.dzi` extension.
My original idea was to also implement writing the dz format to a buffer using the ZIP container, but it's currently not possible, because Vips lacks the required `dzsave_buffer` function (see jcupitt/libvips#415).
=> Add support for writing dz format to zip container

docs/install.md
Amazon introduced [Node.js 4.3 support for Lambda](https://aws.amazon.com/de/blogs/compute/node-js-4-3-2-runtime-now-available-on-lambda/), which is now the recommended runtime instead of the old Node.js 0.10. This commit revises the Lambda docs to build Node.js 4.3 compatible binaries using the latest stable [Node.js 4.x packages from Nodesource](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora).
=> Update Lambda instructions for Node.js 4.3

binding.gyp
Can also be set in .npmrc.
Closes: https://github.com/lovell/sharp/issues/442
=> Allow node-gyp configure --sharp-cxx11=1

docs/changelog.md
Deprecated style of calling extract was removed in 2034efcf558bbb0a6936b1804c0422103d43ad69
=> Document undocumented BC break in v0.14.0

docs/api.md
Tiny pr to document something that I initially found confusing. I expected 
```javascript
sharp(input).raw().toFile('c.raw');
```
to write a raw dump of the image in uint8, but instead I get an error:
```
Unhandled rejection Error: Unsupported output format c.raw
at Error (native)
```
=> Update docs to better reflect output of RAW data

src/pipeline.cc, test/unit/extractChannel.js
This small pr moves the `boolean()`, `bandbool()`, and `extractChannel()` operations to before the code that performs sRGB conversion. It doesn't make sense to be able to extract a channel that doesn't appear in the input image. It also doesn't make a lot of sense to perform boolean operations on channels that were implicitly added after the image was loaded. This does raise the somewhat odd potential for colorspace conversion to be performed after a bitwise boolean operation -- perhaps this should be explicitly prevented? It can happen if the input image has a non-sRGB profile.
=> Change the order of operations: boolean, extractChannel, then sRGB conversion

src/operations.cc, test/unit/bandbool.js
This small PR fixes a bug where `bandbool()` produces a 1-channel sRGB image. Without `toColourspace()` there should be no way to get a 1-channel image out of sharp. I've added a test case for this and modified the existing test cases to accept 3-channel images until `toColourspace` can be merged.
=> Make sure bandbool does not create 1-channel 'sRGB' images

package.json, src/pipeline.cc, test/unit/overlay.js
These changes allow to composite opaque images, applying the commit @strarsis has mentioned.
=> Allow overlayWith source without an alpha channel #506

binding.js
We are using sharp on an embedded platform, and we need to cross compile on Jenkins when we create a debian package. Right now, binding.js reads the host's arch, arm_version and platform, this enables us to specify them as command line args to `npm install` i.e. `npm install --arch=arm --armv=7 --platform=linux`
=> Allow for overriding platform, arch and arm_version

lib/output.js, package.json, src/pipeline.cc, src/pipeline.h, test/unit/tile.js
This PR adds format propagation to the tile output, fixing https://github.com/lovell/sharp/issues/337. Specifically, it forwards the output format and output format options through the suffix argument to vips. Format propagation only occurs if explicitly set (i.e. not `input`), otherwise it defaults to the current behavior of `jpeg`.
I've only added support for `jpeg`, `png` and `webp` since those seem like the most desirable tile formats. Also, when using `jpeg` with Google or Zoomify layouts, the `.jpg` extension is used instead of `.jpeg` as per [libvips defaults](https://github.com/jcupitt/libvips/blob/6bff578fd978bace5959e894341809628928c0b5/libvips/foreign/dzsave.c#L1677) and to maintain compatibility.
Usage looks like this:
```js
sharp('huge-map.svg')
.background('transparent') …
```
=> propagate format to tile output

binding.gyp
Fixes: #655
However, since i did not understand all the line i simplified, i may have removed something.
=> Simpler expression for finding vips-cpp libdir

docs/install.md
As recommended in #81, add a CLI tools section to the installation guide.
=> Add CLI tools section to installation guide

docs/install.md, package.json
Hey guys, we've created over at TailorBrands a few docker files based on Debian Jessie for libvips 8.4.6 and 8.5.5 and also pre-baked node.js images as well,
We're happy to share them and maintain them as we use Sharp ourselves!
=> add Debian jessie based dockerfiles links to the documentation

docs/api-utility.md, lib/utility.js
Skimming the documentation I wasn't sure if caching occurred by default. It does. I've updated the documentation to reflect this better.
=> Clarifying cache documentation

binding.js, package.json
=> Migrate from got to simple-get

lib/index.js
Dynamic require statements make it more difficult for a bundler to figure out the needed modules. In this case there's not much benefit in code reduction either, so just revert to static strings inside the require statement.
This (together with providing a list of dlls to include) makes it possible to bundle a nodejs application using sharp into a stand-alone executable using nexe.
=> Facilitate bundling of sharp

docs/api-resize.md, lib/resize.js
The `withoutEnlargement()` and `max()` methods are the ones that, together, will match ImageMagick's behaviour. I added a mention to `max()`, which I would have found helpful.
=> Adding mention of max() to preserve ratio in withoutEnlargement

lib/output.js, package.json, src/pipeline.cc, src/pipeline.h, test/unit/tile.js
following back from issue: https://github.com/lovell/sharp/issues/1115
I exposed the angle argument for the .tile() function. It didn't really solve my problem, but it rotates the image. It looks equivalent to do .rotate() before .tile()
=> Tiling angle support

docs/install.md, lib/libvips.js, test/unit/libvips.js
=> Skip libvips compilation with SHARP_IGNORE_GLOBAL_LIBVIPS env var

docs/api-output.md, lib/output.js, test/unit/io.js
This PR addresses #1207, with one concern mentioned below. Any insight/feedback is appreciated.
It isn't clear to me why the test case required `.toColourspace('b-w')` to compress properly. If we check the input document's metadata, the space is already 'b-w'.
Output of fixtures.inputTiff metadata:
```js
{
format: 'tiff',
width: 2464,
height: 3248,
space: 'b-w',
channels: 1,
depth: 'uchar',
density: 300,
hasProfile: false,
hasAlpha: false,
orientation: 1
}
```
=> Add Group 4 (CCITTFAX4) compression to TIFF output

lib/constructor.js, lib/output.js, src/pipeline.cc, src/pipeline.h, test/unit/io.js
This exposes the `optimize_coding` flag from libvips, which was previously hardcoded to always be `TRUE`. By default this still remains enabled, but now it's possible to disable optimisation.
My use case is https://github.com/lovell/sharp/issues/846#issuecomment-398883207, I want to generate JPEG files with a constant header.
Admittedly this is a very small and particular use case, and I would understand if you don't want to expose this option in the library, but it would really help me.
=> Expose the optimize_coding flag libvips as an option

docs/api-output.md, lib/constructor.js, lib/output.js, src/pipeline.cc, src/pipeline.h, test/unit/io.js
This exposes the quant_table flag from mozjpeg, which previously had the libjpeg/mozjpeg default of `0`. Will use `0` as the default, but now it's possible to choose a specific quantisation table when paired with the `optimize_coding` flag that was recently added.
This can be very useful in a certain cases where some tables provide a better quality/compression ratio for certain images, which opens up a few cool tricks.
I unfortunately could not figure out a way to run the tests in a reliable way since mozjpeg is usually not installed, but it seems other tests using mozjpeg features use a similar "same or less" approach - let me know if you have any pointers on how this can be improved. Perhaps if there was some way to check if mozjpeg is available, it could be exposed by sharp somehow and …
=> Expose mozjpeg quant_table flag

lib/output.js
As specified [in code](https://github.com/lovell/sharp/blob/master/lib/output.js#L267) webp alphaQuality range is 1-100, not 0-100
=> docs: fix webp alphaQuality range

docs/api-constructor.md, lib/constructor.js
Alpha for the JS color module is between 0-1, not 0-255.
=> Updated the "make a transparent image" example

docs/api-output.md, lib/output.js, src/pipeline.cc, src/pipeline.h, test/unit/tile.js
Hi Lovell,
Stumbled across this issue while using sharp https://github.com/lovell/sharp/issues/1281 and thought I'd have a bash at it...
I don't see 'teeth' in the list of branches as a target for this pull request, am I missing something or am I right to use master (it should be non-breaking but it is a change/addition to the api)
Since libvips chooses a default depth based on the layout detected, I thought it best that sharp didn't choose one itself and instead not provide anything unless explicitly set in the javascript.
Alun.
=> Pass tile depth parameter down to libvips

src/common.cc, src/common.h, src/pipeline.cc
While working on the rotation feature I came across a 25-line segment that was duplicated and that I probably will need to duplicate again, so I thought I might as well move it into a reusable function.
It's neither a bugfix nor a new feature, so tests stay the same.
If you prefer me including this in the rotation PR, let me know, but I thought it was more proper to do it separately.
=> refactor: Move background extraction into separate method.

docs/install.md
This will help folks having installation issues on windows resolve without opening an issue.  This issue has been seen in Issue #1382  #1387  and in https://github.com/gatsbyjs/gatsby/issues/8325
=> Clear _libvips cache on windows

docs/install.md
With version 8.7.0 of the vips-dev Alpine package the documented installation instructions no longer work and result in:
ERROR: unsatisfiable constraints:
pc:fftw3 (missing):
required by: vips-dev-8.7.0-r0[pc:fftw3] vips-dev-8.7.0-r0[pc:fftw3] vips-dev-8.7.0-r0[pc:fftw3]
The fix was proposed in https://bugs.alpinelinux.org/issues/9561#note-2
=> Update Alpine libvips installation instructions

docs/api-resize.md, docs/changelog.md, lib/resize.js, package.json, src/pipeline.cc, test/unit/resize.js
Pull request for #1432. Adds newly available (as of libvips 8.7.0) Mitchell-Netravali spline as a resize kernel option.
=> Add mitchell kernel

lib/channel.js, lib/colour.js, lib/input.js, lib/operation.js, lib/output.js, lib/resize.js
That should solve the issue. All unit tests are passing on my machine. I wasn't able to control if there were no other issues in the code regarding minification compatibility since `msbuild` is being particularly difficult when I reference `sharp` as a `file:` dependency.
=> Do not rely on function names to populate Sharp's prototype so that the library can be minified. Fixes #1474.

docs/api-composite.md
Fix the documentation to inform `overlay` parameter is optionnal.
=> Update `overlay` as optionnal parameter

docs/api-resize.md, lib/resize.js
Came across this while copy-pasting the extend example.
=> Add missing comma to `extend` example

docs/api-constructor.md, lib/constructor.js, src/common.cc
The page parameter is considered also when loading a pdf
=> Set page option for pdf

docs/api-composite.md, lib/composite.js
I found an error in docs for `composite` method. The `create` object should be documented under `images[].input` not inside `images[]`. No changes to the code itself.
=> Change docs for `composite` to reflect how `create` works

lib/constructor.js
Added a friendly error message in case the require to the bindings throws for any reason. The error message looks like this:
```
"sharp" does not seem to have been built or installed correctly.
- Try to reinstall packages and look for errors during installation
- Consult "sharp" installation page at http://sharp.pixelplumbing.com/en/stable/install/
If neither of the above work, please open an issue in https://github.com/lovell/sharp/issues
```
Fixes https://github.com/lovell/sharp/issues/1624
=> Add warning if sharp bindings aren't built correctly

docs/api-output.md, lib/output.js, package.json, src/pipeline.cc, src/pipeline.h, test/unit/tile.js
Hi!
Here it is ! 
* I didn't upgrade the libvips in the package.json version
* It seems that upgrade libvips to 8.8.0 broke 2 tests (`Image metadata ->  JPEG with IPTC/XMP` and `Attention strategy -> JPEG`) It also appears with master when libvips 8.8.0 is activated. I didn't fix them because i don't underestand their purposes ...
* I had to force the the skipBlanks in output.js because `AttrTo<int32_t>(options, "skipBlanks")` return 0 if it's NULL/undefined
Let me know if it needs some modifications.
=> add skipBlanks support for dz and zoomify layout

lib/output.js
I used a Map instance to store format correspondances. Seemed to make eveything a bit clearer.
=> Have toFormat accept heic/heif (#1824)

.travis.yml, appveyor.yml
https://nodejs.org/en/blog/release/v13.0.0/
=> Add Node 13 to CI

docs/api-output.md, lib/constructor.js, lib/output.js, package.json, src/pipeline.cc, src/pipeline.h
I've done the best I can to add background colour as an option for the tile() method. I may have missed something here as I'm not a C++ programmer. Let me know your thoughts. Thanks.
=> Add background colour option to tiles operation (#1923)

lib/output.js, package.json, test/unit/tile.js
This merge request addresses #1918, a tile overlap regression spotted in `v0.23.0` and higher.
I've made the change needed to fix the regression, I've also added a test to prevent it from happening again.
Let me know if there are any improvements that I can make, this is my first PR for Sharp!
=> Ensure tiles have overlap applied

src/pipeline.cc
`stat64` does not exist on FreeBSD.
=> FreeBSD uses stat instead of stat64

package.json, src/pipeline.cc, test/unit/resize.js
Fix re #2020
When the `withoutEnlargement` option is set to true the pipeline *should* now bind the input image's width and height as maximum.
Previously if one value was in bounds and one was out of bounds, then the output image would keep the dimensions of the input image.
Also added two unit tests to back this.
=> Correctly bind max width and height values when using withoutEnlargement

docs/api-input.md, lib/input.js
It's hard to tell from the docs whether `stats.isOpaque` means that all pixels are 100% opaque, or if it means at least one pixel is not 100% transparent.
=> Clarify stats.isOpaque

docs/api-output.md, lib/output.js
Came across this while updating the typings for DefinitelyTyped, in the example for `.raw()` the method `.colourspace()` is called, which I think should be `.toColourspace()` instead?
=> docs: change 'colourspace' to 'toColourspace'

install/libvips.js
ISSUE 2105: Added the possibility to set the host for downloading the binary in a way similar to 'prebuild' and 'node-pre-gyp'.
Left in the previous additions using 'sharp_dist_base_url' and 'SHARP_DIST_BASE_URL' to not break working installations.
=> ISSUE 2105: Added the possibility to set the host for downloading the binary

src/common.cc
`libvips` uses specific loaders for ImageMagick 7.
=> Add support for ImageMagick version 7

src/common.cc
ICO files, for instance, may have multiple pages, which can be selected when loading a file through ImageMagick.
=> Allow page selection when loading a file through ImageMagick

binding.gyp, install/dll-copy.js, install/libvips.js, lib/libvips.js, lib/utility.js, package.json
This PR adds supports for a single shared libvips library with its dependencies statically-linked as described in PR https://github.com/lovell/sharp-libvips/pull/44 and issue https://github.com/lovell/sharp-libvips/issues/39.
I've also included several other enhancements:
- Set the minimum macOS deployment target to 10.9 (Mavericks) which is a good balance between features and compatibility. Starting with 10.9, Apple has made libc++ the default, so it is no longer necessary to set `CLANG_CXX_LIBRARY`. Note that [Node v12 has set this variable to 10.10](https://github.com/nodejs/node/commit/a7d7d4dfb73233b23e478c73d6fff784a0738b9b).
- Link the dependencies with a fully-qualified soname (e.g. `libvips.so.42`) as the symbolic links in the tarball are dereferenced now.
- Unpack the prebuilt …
=> Add support for statically-linked dependencies (lovell/sharp-libvips#39)

lib/input.js, test/unit/gif.js, test/unit/webp.js
=> fix: Animated GIF to WEBP using a Sharp stream is not animated anymore

install/libvips.js
The version check added in https://github.com/lovell/sharp/commit/d406cb619c9a9db336f138b58bfde267e573e1ce expects `process.env.npm_package_engines_node` to exist. Yarn 2 (not sure about v1) doesn't expose fields from `package.json` like `npm` does, so the build instantly fails, rendering 0.26.1 uninstallable.
I've added a fallback that reads and parses `package.json` directly if the expected variable isn't found.
=> Avoid install script crashing on Yarn

.travis.yml, appveyor.yml
Shamelessly based on this commit: https://github.com/lovell/sharp/commit/edf3fe24c97da74f6a9a29a09a267f9d49b06834
=> CI: add Node.js 15

package.json
Adds support for npm 7; see release notes for [6.0.0](https://github.com/prebuild/prebuild-install/releases/tag/v6.0.0).
See discussion at #2415 for stack traces, examples, etc.
=> Upgrade to prebuild-install 6.0.0

README.md, docs/README.md, docs/install.md, install/libvips.js, package.json
This PR conditionally downloads the libvips tarball in Brotli or gzip format, depending on whether the user's version of Node supports Brotli decompression. This allows the minimum Node version to revert to 10.
Fixes #2410
=> Conditionally download Brotli or gzip

docs/api-constructor.md, lib/input.js, package.json, src/common.cc, src/common.h, test/unit/noise.js
Gaussian noise feature respecting the [proposed API](https://github.com/lovell/sharp/pull/2525#issuecomment-757448918)
```javascript
sharp({
create: {
width: 1024,
height: 768,
channels: 1,
noise: {
type: 'gaussian',
mean: 128,
sigma: 30
}
}
});
```
=> feat: exposing vips_gaussnoise operation

lib/utility.js
Some bundlers (in my case, rollup v2 with commonjs plugin) tend to rename lib variables for some reason like shown in the sample output code below:
```
/**
* Decorate the Sharp class with utility-related functions.
* @private
*/
var utility = function (Sharp) {
[
cache$1,
concurrency,
counters,
simd
].forEach(function (f) {
Sharp[f.name] = f;
});
Sharp.format = format;
Sharp.versions = versions$2;
Sharp.queue = queue;
};
```
This obviously leads to TypeError when trying to call e.g. sharp.cache(false). Could be an issue with Terser or other minifier as well.
The quick fix is to change the way it gets assigned (in PR).
=> Change utility-related functions assignment way

test/unit/extractChannel.js
The description of the last unit test in `test/unit/extractChannel` is misspelled.
=> Tests: fix unit test description

docs/api-operation.md, lib/operation.js
I just noticed that the docs show `flatten` with a string.
`flatten` expects an options object with background property,  passing a color string always results in black background.
=> flatten jsdoc: object instead of string

lib/agent.js, test/unit/agent.js
Hello,
When we install `sharp` module on a machine which is behind a proxy, we have an error  `ERR! sharp tunneling socket could not be established, statusCode=407` if the password contains special characters.
This problem is because the `agent()` function returns a `password`where special characters are encoded. 
To fix this problem, we just need  to decode password before to return it. 
Open to any suggestions of course.
=> install: fix proxy authentication when password contains special character

docs/install.md
Changed `Alibaba provide a mirror site` to `Alibaba provides a mirror site`.
=> Fix minor grammatical error in Installation docs

docs/install.md, install/libvips.js
I would like to create cross platform bundles including sharp prebuilds, e.g. installing sharp for darwin-x64 on a linux-arm64 machine. For that reason the libc checks needs to be disabled - or the installation needs to be forced.
I am aware that this flag is kind of I-know-what-I-am-doing - I am open for discussions
And again: Thank you for this great library :-)
=> Allow cross platform installation by custom libc flag

lib/constructor.js, lib/input.js, lib/is.js, lib/output.js, src/common.cc, src/common.h, src/pipeline.cc, src/pipeline.h, test/unit/raw.js
Fixes https://github.com/lovell/sharp/issues/1454 and fixes https://github.com/lovell/sharp/issues/1289. I've mostly added just the logic to support input or output raw data in different bit depths for now. If you like it, I'll also adjust the documentation accordingly and ensure test coverage of course.
***
```javascript
const input = new Uint16Array( 48 );
for ( let i = 1; i < 48; i += 3 ) {
input[ i ] = 0xffff;
}
sharp( input, {
raw: {
width: 4,
height: 4,
channels: 3,
},
} ).toFile( "16bpc.png" );
```
This generates a green 4x4 .png file with 16 bits per pixel per color.
***
```javascript
sharp( "16bpc.png" )
.toColourspace( "rgb16" )
.raw( {
depth: "ushort",
} )
.toBuffer( ( error, data, {
width,
height,
channels,
size,
} ) => {
console.log( size / width / height / channels * 8 ); …
```
=> Add support for different bit depths with raw input and output

src/common.cc
This is a fix for #2864. I've updated my [reproduction repo for that issue](https://github.com/paulstraw/sharp-magick-lambda) to point at this branch, and it does indeed fix the bug.
=> Add ImageMagick 7 loaders

lib/output.js, test/unit/io.js
This fixes an issue where if you try to write to the same destination as the input file but you are not using absolute (or the same relative path) for both the input and output, sharp/vips might produce errors such as:
```
someFile.jpg: unable to open for write
unix error: No such file or directory
```
Fixes #2873
=> Resolve paths before comparing input/output destination

docs/api-output.md, lib/output.js, test/unit/heif.js
Fixes #2861
Do we need to check for specific versions of libvips or libaom, or is this fine as it stands?
=> Allow using speed 9 for AVIF/HEIC encoding

lib/output.js, test/unit/io.js
Should solve #2775 by adding an alternative `tif` format for `tiff`.
Added a unit test which calls `toFormat('tif')` and asserts format is `tiff`.
=> Allow alternate tif format for tiff for #2775

docs/install.md
https://zhuanlan.zhihu.com/p/432578145
The old domain will be out of service on 2022.05.31.
`npm.taobao.org => npmmirror.com`
=> Docs: Chinese mirror domain deprecated

lib/output.js, test/unit/io.js
=> Emit close event when stream is complete

binding.gyp, src/sharp.cc, test/unit/io.js
Context: #2999 and https://github.com/libvips/libvips/pull/2571.
=> Windows: make invalid param errors recoverable by default

src/pipeline.cc, test/unit/affine.js, test/unit/resize-cover.js, test/unit/rotate.js, test/unit/trim.js
@kleisauke as we discussed in https://github.com/lovell/sharp/pull/2789#issuecomment-985072211
I didn't apply this to the `composite` operation as this should still work, plus can be used to watermark an animation via tiled composition.
=> Ensure operations without multi-page support reject rather than silently fail

package.json
According to [Snyk's vulnerability page](https://security.snyk.io/vuln/SNYK-JS-SIMPLEGET-2361683), simply updating `simple-get` package version to fix this vulnerability.
=> Vulnerability: update simple-get package version

src/pipeline.cc, test/unit/webp.js
Otherwise, it could lead to funny results.
<details>
<summary>Before / after examples</summary>
```bash
$ curl -LO https://storage.googleapis.com/downloads.webmproject.org/webp/images/dancing_banana2.lossless.webp
$ node -e "require('sharp')('dancing_banana2.lossless.webp', { pages: -1, page: 2 }).resize(128).toFile('x.gif')"
```
| Before | After |
| :---: |  :---: |
| ![before](https://user-images.githubusercontent.com/12746591/151360287-b3b9934b-8608-4cd3-87e4-9a6870078b3c.gif) | ![after](https://user-images.githubusercontent.com/12746591/151360320-6eec28be-1f1c-4c3b-b6b1-2c206a3b2164.gif) |
</details>
A test case was added to prevent further regressions.
=> Take page parameter into account when all frames are read

src/pipeline.h, test/unit/webp.js
By not initializing the delay vector, since we assume it's empty by default  in `SetAnimationProperties`.
https://github.com/lovell/sharp/blob/68823a5edb0c913fb230cd36c1ce22554e48f9ad/src/common.cc#L495-L503
A test case was added to prevent further regressions.
See: #3061.
=> Ensure delays of the origin image is preserved

src/common.cc, src/common.h, src/pipeline.cc, test/unit/resize.js
Ensures that it does not interfere with cropping/embedding.
See: #3067.
=> Move `withoutReduction` logic to `ResolveShrink`

src/pipeline.cc, src/pipeline.h
=> Ensure `affineInterpolator` is correctly finalized

lib/input.js, test/unit/io.js
=> [#3145] byteOffset of typedArray is not handled properly

package.json, src/common.cc, test/unit/io.js
Fixes #2360
This PR updates the error message 'Input file is missing' to include the file that is missing.
=> Add missing file name to 'Input file is missing' error message

docs/api-output.md, lib/output.js
Removed an extra `)` on code example for converting to `gif`
=> Fix typo in api-output.md

docs/install.md, install/libvips.js, package.json
Changes include
- Feature to install the prebuilt libvips binaries from a directory on the local filesystem
- Installation doc update
- Separate instructions for prebuilt sharp and libvips binaries to avoid confusion
- Added instructions to install prebuilt libvips binaries from local filesystem directory
Closes https://github.com/lovell/sharp/issues/3188
=> Feature to use locally downloaded libvips

docs/install.md, lib/platform.js, package.json, test/unit/platform.js
This is a sibling PR to PR in upstream dependency [prebuild-install](https://github.com/prebuild/prebuild-install/pull/176) and should fix #3159.
=> Allow specifying libc for Linux install

src/pipeline.cc, test/unit/extract.js
the fix for #3024 isn't handling exif orientation 2 correctly
orientation 2 is flipped but has no rotation and wasn't applied correctly because of that
=> fix rotate-then-extract for EXIF orientation 2

docs/api-input.md, lib/input.js
The example is wrong. `>=` has precedence over `||` so the example always switchs the width and height if orientation has non-zero value and this leads to incorrect size.
=> docs(input): correct getNormalSize with EXIF orientation example

lib/output.js, test/unit/webp.js
Setting WebP effort to 0 in the constructor caused the effort to use the
default value of 4.
=> Fix setting WebP effort to 0 in constructor #3259

src/pipeline.cc, test/unit/resize.js
When scaling WebP images up past 16383 x 16383 use vips scaling logic to prevent `Error: webp: bad image dimensions`
Fixes #3262
=> Use vips to upsample webp 

docs/api-composite.md, docs/api-constructor.md, docs/api-output.md, lib/composite.js, lib/constructor.js, lib/input.js, lib/output.js, package.json, src/common.cc, src/common.h, src/pipeline.cc, test/unit/text.js
Hello @lovell ,
This a PR regarding the vips_text feature (#512)
Some notes about this PR :
- I started from your [last proposal API](https://github.com/lovell/sharp/issues/512#issuecomment-817599154)
- What @rorz did helped me getting started and  i removed all the color related stuffs but integrated the rgba option
- maybe the spacing parameter should be renamed as lineSpacing ?
- I did not take into consideration the [autofit_dpi](https://www.libvips.org/API/current/libvips-create.html#vips-text) parameter exported by libvips. Should i ?
- Regarding the tests
- I have all my new tests passing but some existing ones are failing (even on your main branch). I tried with libvips installed via brew and recompiled locally with no success.
- I added a font (Bitstream Vera from the Gnome …
=> Expose vips_text to create an image containing rendered text #512

.github/workflows/ci-darwin-arm64v8.yml, .github/workflows/ci.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

docs/api-resize.md, lib/resize.js
Just a little update to avoid confusing fit as a valid keyword for the transformation request
=> Update word format in resize docs

lib/output.js, test/unit/jp2.js
Fixes couple of minor issues with JP2 errors:
1. The tests passed as false-positives even if regex is changed to arbitary pattern, because the promise returned from `assert.rejects` was ignored and the test ended prematurely. This is fixed by removing `{ ... }` around the test function body.
2. This, in turn, hid an issue with `toFile` not throwing the expected error message which was instead propagating `Error: VipsOperation: class "jp2ksave" not found` from libvips. This is now fixed by manually checking the extension before calling into libvips.
3. Pre-creating error instances like `errJp2Save` did is sometimes tempting, but is problematic for debugging because it hides the actual stacktrace of the error (the stacktrace is collected at the moment of `new Error` creation). This is now …
=> Fix errors for missing OpenJPEG

.mocharc.jsonc, package.json
- Run tests in parallel. On my ThinkPad laptop with 8 cores, this reduces tests execution time from 60-70 seconds to 30-35 seconds (essentially ~2x faster turnaround).
- Move Mocha settings to a config file. This allows to easily invoke Mocha alone via `npx mocha`, or for e.g. VSCode Test Explorer to find & run tests with the correct settings automatically.
=> Run tests in parallel

docs/api-constructor.md, lib/constructor.js
Clarification to the `failOn` setting coming from the discussion in https://github.com/lovell/sharp/issues/3480. Goal of this PR is to set correct expectations of when `failOn` is actually applied internally and which images are always expected to fail regardless of the setting of this
Fixes https://github.com/lovell/sharp/issues/3480
=> chore(docs): Clarify `failOn` setting

.github/CONTRIBUTING.md, lib/index.d.ts, package.json, test/types/sharp.test-d.ts, test/types/tsconfig.json
Treat this as a work-in-progress that we can use to base our discussions from.
Addresses #3369
In essence, this lifts the types from the `@types/sharp` module into the official package, along with the tests that were in that package as well.
Because the types reference node.js types such as `Buffer`, we also need to add a new dependency: `@types/node`. The DefinitelyTyped modules uses the wildcard version range (`*`) in order to prevent multiple copies of the package in the module tree, which often leads to hard to diagnose problems. An alternative would be for us to use `>=14.0.0` or similar. Open to suggestions.
As @lovell pointed out in #3369, this should be considered a minor breaking change, so should likely be released as 0.32.0. When that happens, we can also deprecate …
=> Include TypeScript definitions in bundle

docs/install.md
Ref https://github.com/libvips/libvips/issues/3274#issuecomment-1406341947
=> Clarify supported bit depth for AVIF images with prebuilt libvips

lib/constructor.js, lib/index.d.ts, lib/input.js, lib/is.js, test/unit/io.js, test/unit/raw.js
Supercedes https://github.com/lovell/sharp/pull/3546
=> Arraybuffer

lib/agent.js, test/unit/agent.js
While debugging an unrelated proxy error, I stumbled upon an incorrect display of the proxy URL. Instead of displaying `http://example.com:1234`, `http:://example.com:1234` is being displayed. This may case some serious confusion.
As far as my understanding goes, this only impacts the actual display within the logs. But I must say that I'm not completely sure of that.
This PR corrects this log line and relevant tests.
=> Fix notation of proxy URL in logs

test/bench/perf.js
Otherwise it'll default to bilinear (`jimp.RESIZE_BILINEAR`), which is faster than bicubic but less accurate.
This corresponds to what is done in the JPEG benchmark suite:
https://github.com/lovell/sharp/blob/0bc79cdb953c9c0f1cf9015be65fb231fd5ec520/test/bench/perf.js#L59
https://github.com/lovell/sharp/blob/0bc79cdb953c9c0f1cf9015be65fb231fd5ec520/test/bench/perf.js#L79
=> Tests: ensure Jimp uses bicubic as the resizing kernel

lib/index.d.ts, test/types/sharp.test-d.ts
For issue https://github.com/lovell/sharp/issues/3747.
The webp output options type is missing the preset values in the types.  They are present in the js library.
This PR adds:
* A new enum  (`PresetEnum`)
* The preset on `WebpOptions`
* The enum as `sharp.preset` on `sharp`.
* Tests for both string and enum based use of `webp({preset: ...})`
This follows the same implementation as other options, such as resize.fit.
npm test-types and npm test-lint both run cleanly.
=> Added webp preset types and test for same. Issue 3747

src/pipeline.cc
musl 1.2.4 has removed the legacy LFS64 glibc-ABI-compat symbols, which would cause an error during `npm install sharp` when compiled from source (either with the `--build-from-source` flag or when a globally installed libvips is detected).
> On the API level, the legacy "LFS64" ("large file support") interfaces, which were provided by macros remapping them to their standard names (`#define stat64 stat` and similar) have been deprecated and are no longer provided under the `_GNU_SOURCE` feature profile, only under explicit `_LARGEFILE64_SOURCE`. The latter will also be removed in a future version. Builds broken by this change can be fixed short-term by adding `-D_LARGEFILE64_SOURCE` to `CFLAGS`, but should be fixed to use the standard interfaces.
> https://musl.libc.org/releases.html
The …
=> Fix build with musl 1.2.4

lib/index.d.ts, test/types/sharp.test-d.ts
While use sharp to convert to WebP with TypeScript, I found the Type Error of `WebpOptions.minSize`.
it param is boolean, but Type specify as number.
So we had going to use `@ts-tsgnore`  when use this option.
This PR corrects this bug.
=> fix Type bug in WebpOptions.

lib/index.d.ts
As I do not know all the possible `options.operations` I left it string[], if you know better, it would be cool to have the valid entries as List of Strings in the declaration.
=> add block and unblock to typescript declaration

.github/workflows/ci.yml
https://docs.python.org/3.11/whatsnew/3.11.html
> Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite.
=> CI: Upgrade to Python 3.11

lib/index.d.ts, test/types/sharp.test-d.ts
=> fix: allow boolean withMetadata argument

lib/sharp.js
Find while investigating issues with https://github.com/nuxt/image/pull/1102
`module.exports` defaults to an empty object `{}`, if no sources are available, we were not detecting it. 
PS: Let me know if you prefer another style for changes.
=> Correctly check for when sharp is unavailable

lib/utility.js
Based on the #3893 issue, there was a setting problem, which is fixed with this modification. If the `process.env.VIPS_NOVECTOR=0`, then simd set `false` in default.
=> Fixed VIPS_NOVECTOR correct work

lib/index.d.ts, test/types/sharp.test-d.ts
This PR adds keepMetaData type to Sharp instance.
See #3908 for more context.
=> Added typescript prompt for keepmetadata

README.md, docs/changelog.md, docs/install.md
Hello!
I'm not too picky on the exact format, so feel free to reformat in a way you prefer, but I found it confusing how the "semver" version mention in the docs wasn't accurate, `>= 18.17.0` implies that any versions after `18.17.0` works, but that is not the case. For instance, someone on `20.2.x` will fail to install Sharp, as will someone on `19.x.x`. 
This caused a few downstream issues in repos I maintain that have Sharp as an `optionalDependencies` because users didn't get an error on install (since it's an optionalDep), but as far as they could tell from the Sharp docs, they had a supported version of Node.
=> docs(install): Write full supported versions

.github/workflows/ci.yml
Emscripten does not guarantee ABI compatibility across its versions, so we need ensure that this version is kept in-sync with the wasm-vips project.
> ```md
> Note that there is *no* ABI compatibility guarantee between versions - the ABI
> may change, so that we can keep improving and optimizing it. The compiler will
> automatically invalidate system caches when the version number updates, so that
> libc etc. are rebuilt for you. You should also rebuild object files and
> libraries in your project when you upgrade emscripten.
> ```
> _From: https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md?plain=1#L7-L11_
Depends on: https://github.com/lovell/sharp-libvips/pull/212.
=> CI: Update Emscripten Docker image to 3.1.51

.github/CONTRIBUTING.md
It seems usejsdoc.org does not exist anymore, and jsdoc.app is the new location.
=> Docs: replace unavailable usejsdoc.org with jsdoc.app

docs/api-constructor.md, lib/constructor.js, lib/index.d.ts, lib/input.js, test/types/sharp.test-d.ts, test/unit/text.js
fix text.wrap typo error  and TypeScript type defined error
=> fix: typo error text.wrap

lib/constructor.js, lib/index.d.ts, lib/output.js, src/pipeline.cc, src/pipeline.h, test/unit/avif.js, test/unit/heif.js
Following #4031, this PR exposes a `bitdepth` setting to allow outputting 10-bit or 12-bit AVIF/HEIF files. The default remains 8, so this doesn't change the current behavior.
Fixes #4031
=> feat: bitdepth option for avif/heif

lib/index.d.ts, test/types/sharp.test-d.ts
`animated` property was missing from declaration types, just added it
=> types: added missing types for OverlayOptions

docs/api-input.md, lib/index.d.ts, lib/input.js, src/metadata.cc, src/metadata.h, test/unit/metadata.js
Read-side implementation of PNG text following the proposed API in #3549, ie
```
comments: [
{ keyword: 'parameters', text: 'highly detailed...' },
{ keyword: 'Copyright', text: 'legal minefield' },
...
]
```
Notes:
* Returns the comments in the order that they're stored in the VipsImage metadata, rather than sorting on the embedded index. It looks like this should give the same ordering under normal circumstances.
* Reuses the existing test fixture `testJoinChannel.png` that happens to already have a comment, in order to keep change size down.
=> Expose input PNG comments in metadata

.github/workflows/ci.yml, docs/install.md, npm/linux-ppc64/package.json, package.json, test/unit/libvips.js
@lovell Built and tested locally.
=> ppc64le support

test/bench/parallel.js, test/bench/random.js
Since `simd(true)` is the default behavior, these can be removed.
https://sharp.pixelplumbing.com/api-utility#simd
=> chore(benchmark): remove simd(true)

.github/workflows/ci.yml
Upgrade `uraimo/run-on-arch-action` to v3, which includes QEMU 9.2.2 from `tonistiigi/binfmt:latest` that fixes the current CI failure on ppc64le - see:
https://github.com/uraimo/run-on-arch-action/issues/160
https://github.com/tonistiigi/binfmt/issues/215#issuecomment-2689340770 
https://gitlab.com/qemu-project/qemu/-/issues/1913
=> CI: Upgrade `uraimo/run-on-arch-action` to v3

lib/libvips.js, test/unit/libvips.js
Before:
```console
$ ls -1 .yarn/unplugged | grep sharp-libvips-linux-x64
@img-sharp-libvips-linux-x64-npm-1.1.0-rc4-5841416c64
$ yarn node -p "require('sharp/lib/libvips').yarnLocator()"
6e8b62218c
```
After:
```console
$ ls -1 .yarn/unplugged | grep sharp-libvips-linux-x64
@img-sharp-libvips-linux-x64-npm-1.1.0-rc4-5841416c64
$ yarn node -p "require('sharp/lib/libvips').yarnLocator()"
5841416c64
```
=> Ensure Yarn PnP hash calculation works with pre-releases

lib/index.d.ts
This PR fixes the following error:
```
node_modules/sharp/lib/index.d.ts(1590,15): error TS2430: Interface 'OverlayOptions' incorrectly extends interface 'SharpOptions'.
Types of property 'autoOrient' are incompatible.
Type 'boolean | undefined' is not assignable to type 'boolean'.
Type 'undefined' is not assignable to type 'boolean'.
```
The bug was introduced in:
- https://github.com/lovell/sharp/issues/4144
- https://github.com/lovell/sharp/pull/4151
=> fix(types): update `autoOrient` type to include undefined

lib/index.d.ts
Hello! This PR is to add two missing properties to `sharp.OutputInfo` that are present for animated images. Comments are copied from the same properties in `sharp.Metadata`.
The test `Animated GIF round trip` in `test/unit/gif.js` references them ([link](https://github.com/lovell/sharp/blob/5b5dfbad776a2d1aba0739eb52f23b7996821682/test/unit/gif.js#L67-L68)), so it does seem intentional for them to be part of the OutputInfo.
This is my first PR for the project, so please let me know if you need more information from me. 
Thanks for all the hard work on this library!
=> fix(types): Add missing properties for animated images

lib/index.d.ts
This PR proposes a small fix to add the missing typescript definition for the `smartDeblock` option introduced in https://github.com/lovell/sharp/commit/8afec170ed81bc840157ecf5d3ee07ae200ffe33.
I'm not entirely sure yet if I should update [`sharp.test-d.ts`](https://github.com/lovell/sharp/blob/701143afb364c1b618422c59ae955f4084651930/test/types/sharp.test-d.ts). Testing for `WebpOptions` seems scattered and there's no test for all options e.g. `smartSubsample`. But I'm happy to add one if needed.
=> Fix(WebP): Add smartDeblock definition to WebpOptions

lib/index.d.ts
This matches the JS code
https://github.com/lovell/sharp/blob/8607ff2f4a5d0f523f57c589378256a626b62c97/lib/resize.js#L69-L78
=> Types: add "linear" to `KernelEnum`

docs/src/content/docs/performance.md
Since version 8.14, libvips no longer uses [`GThreadPool`](https://docs.gtk.org/glib/struct.ThreadPool.html).
https://www.libvips.org/2022/12/22/What's-new-in-8.14.html#faster-threading
=> Docs: libvips manages its own thread pool
