index.js
src/pipeline.cc
test/unit/crop.js

Adds new gravity options: `northeast`, `southeast`, `southwest`, `northwest`.

Add corner gavity support

---

binding.js
packaging/lin/Dockerfile

Tested with Debian Wheezy and Ubuntu Vivid.

Linux Dockerfile: Use Debian Wheezy as the base image

---

index.js
test/unit/crop.js

Closes https://github.com/lovell/sharp/issues/350

Fix: default crop gravity to sharp.gravity.center

---

index.js
src/pipeline.cc
test/unit/extract.js

This pr addresses the error message seen in #509

Prevent boolean errors during extract operation (#509)

---

lib/operation.js

fixed issue: https://github.com/lovell/sharp/issues/673

rename a to alpha in background color option

---

lib/resize.js
src/pipeline.cc
test/unit/interpolation.js

As recommended in [#731](https://github.com/lovell/sharp/issues/731)

Add support for the "nearest" kernel for image reductions

---

docs/install.md

folder size checked using `heroku run bash`

Add some more heroku info

---

binding.js

update bindings.js for supporting Solus

---

docs/install.md

Added Coding tools section and added types link (#931)

---

lib/input.js
lib/resize.js

Changed jsdocs for withoutEnlargement and sequentialRead as per conversation on issue #972

Changed jsdocs for withoutEnlargement and sequentialRead

---

lib/input.js

Mention EXIF orientation in metadata's jsdocs

---

docs/rebuild from NW.js.md

refers to https://github.com/lovell/sharp/issues/1223

rebuild doc for NW.js

---

README.md

new Buffer() has been depreciated.
fixes #1272

Changed new Buffer() to Buffer.from()

---

install/libvips.js

I have commit a pr for https://github.com/lovell/sharp/issues/1418.

support npm_config_sharp_dist_base_url

---

docs/api-resize.md

fixed a mistake in api-resize.md

fixed a mistake in api-resize.md

---

appveyor.yml

Documentation: https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs

Add Node 12 to AppVeyor builds

---

lib/is.js

I just simplified a couple helpers

Simplify helpers

---

install/libvips.js

The libvips install script should fail when the connection closes before the response is complete. The existing script quietly terminates in this case, leaving the tempfile behind; the `error` and `close` listeners for `tmpFile` do not execute. The failure of the installation may not become apparent until the user hits errors like
```
libvips-cpp.so.42: cannot open shared object file: No such file or directory
```
later while trying to use `sharp`.

Install: fail on incomplete download and clean up tempfile

---

lib/input.js
package.json
test/unit/io.js
test/unit/raw.js

Detect empty input and throw a helpful error

---

lib/input.js

Fixes #2803
Hopefully this makes the usage a bit clearer. Feel free to change the order/wording.

Docs: add stats usage note and example (#2803)

---

lib/input.js

add example of how to get the right-side-up width/height

---

docs/api-resize.md
lib/resize.js

take priority -> takes priority

Fix minor typo

---

src/common.cc
src/common.h
src/pipeline.cc
test/unit/rotate.js

Simplify 90/270 orient-before-resize logic

---

test/unit/composite.js

chore: Fix typo s/implict/implicit

---

test/types/sharp.test-d.ts

Fix typo s/introducted/introduced/
(Forgot to add it on my previous PR)

chore: Fix typo s/introducted/introduced/

---

lib/index.d.ts

change chromaSubsampling type to be a union with undefined

fix(types): chroma-subsampling can be undefined

---

lib/libvips.js

Noticed this while reviewing commit e922ef7450eb17ea52fe7b549147e85874bc6338.

Improve install error help text for ppc64le architecture

---

src/common.cc
src/common.h
src/stats.cc

See the individual commits for more details.

Minor simplifications

---

src/pipeline.cc

Ensure SVG scale-on-load optimisation uses newly exposed params

---

docs/src/content/docs/api-output.md
lib/constructor.js
lib/index.d.ts
lib/output.js
src/pipeline.cc
src/pipeline.h
test/unit/tiff.js

Solves #4421 
I cannot provide full unit test coverage, but I tested locally with a 8 GB image passing the commented out tests, so do with those what you will.
I obviously cannot upload a 8 GB image to the repository nor elsewhere, since the file is confidential, and I haven't found a good way to create a large enough image in test to cross 4 GB when using compression.

BigTIFF support
